# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf4956a1f019aa463c44c720b8307ede138ff665301a06c37f2b478092e6ec32fe47cb2c532d2617c12579070d223ac7b65a6399cdf4128d7208ac390f8269e

test:
  secret_key_base: e7d20bcea8efa793e6745e8bfa6d4707619fae3f97be9c086012f438d61b84b2bad9d92796c93fac3d0b3dd13ee3c4eebec5540fc31b00a954985ef41be774b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
